from django.urls import path
from MainApp import views

urlpatterns = [
    path("",views.index,name='Index'),
    path("3D/",views.three_D,name='3D'),
    path("about/",views.about,name='About'),
    path("AI_blog/",views.AI_blog,name='AI-Blog'),
    path("chatbot/",views.chatbot,name='Chatbot'),
    path("cluster/",views.cluster,name='Cluster'),
    path("contact/",views.contact,name='Contact'),
    path("e-commerce-development/",views.E_commerce_development,name='E-Commerce-Development'),
    path("embedded/",views.Embedded,name='Embedded'),
    path("healthcare/",views.healthcare,name='Healthcare'),
    path("imagerecognition/",views.imagerecognition,name='Imagerecognition'),
    path("intranet_solution/",views.Intranet_solution,name='Intranet-Solution'),
    path("machinelearning/",views.machinelearning,name='MachineLearning'),
    path("mobile_application_development/",views.mobile_application_development,name='Mobile-Application-Development'),
    path("NLP/",views.NLP,name='NLP'),
    path("PCB/",views.PCB,name='PCB'),
    path("product/",views.Product,name='Product'),
    path("python/",views.Python,name='Python'),
    path("robotic/",views.Robotic,name='Robotic'),
    path("robotics_blog/",views.Robotics_blog,name='Robotics-Blog'),
    path("salesforce_system/",views.salesforce_system,name='Salesforce-System'),
    path("SEO/",views.SEO,name='SEO'),
    path("smart/",views.Smart,name='Smart'),
    path("software_development/",views.Software_development,name='Software-Development'),
    path("STEM/",views.STEM,name='STEM'),
    path("training_pages/",views.training_pages,name='Training-Pages'),
    path("web_blog/",views.web_blog,name='Web-Blog'),
]